# Wordle Solver

In [1]:
# import functions
from wordle_helpers import *

In [2]:
# help(main)

In [3]:
# Main function that returns a list of possible words
green_letters = 'AE'
green_positions = [3,5,]
yellow_letters = 'RN'
yellow_positions = [2,4,]
bad_letters = 'C'

# Main function that returns a list of possible words
words = main(green_letters, green_positions, yellow_letters, yellow_positions, bad_letters)
print(words)

['snare']


In [4]:
# Repetitive letters
letters_df = repetitive_letters(wordle_list=words)
print(letters_df.to_string(index=False))

Letters  Count
      S      1
      N      1
      A      1
      R      1
      E      1


#### Choosing next word

In [5]:
# Main function that returns a list of possible words
green_letters = ''
green_positions = []
yellow_letters = 'OHIST'
yellow_positions = []
bad_letters = ''

# Main function that returns a list of possible words
words = main(
    green_letters,
    green_positions,
    yellow_letters,
    yellow_positions,
    bad_letters,
    wordle_list_path="wordle-possible-words",
)
print(words)

['hoist', 'hotis']


In [6]:
# help(score)

In [7]:
df = load_data(file_name='wordle_ranking.csv')
df

Names  Games_Won
0   Murilo        174
1  Barbara         74
2     Draw        176

In [8]:
# Update score
score_df = score()
score_df

Names  Games_Won
0   Murilo        174
1  Barbara         74
2     Draw        177

In [9]:
# Print results
print(score_df.to_string(index=False))

  Names  Games_Won
 Murilo        174
Barbara         74
   Draw        177


In [10]:
# help(reset_score)

#### Set custom score

In [11]:
# help(set_score)

In [12]:
# # Set custom score
# df = set_score(m_score=168, b_score=74, draw_score=168)
# df

#### Reset score

In [13]:
## Reset score
# reset_score()

In [14]:
# Matrix X
X = np.array([
    [200, 150, 150],
    [100, 50, 100],
    [25, 25, 10],
])

# Matrix K
K = np.array([
    [1, 0, -1],
    [2, 0, -2],
    [1, 0, -1],
])

# Performing computations
matrix_mult = X @ K # matrix multiplication
hadamard_prod = np.sum(X * K) # sum of Hadamard product

# Results
print(f"Matrix Multiplication:\n{matrix_mult}\n")
print(f"Sum of Hadarmard product: {hadamard_prod}")

Matrix Multiplication:
[[ 650    0 -650]
 [ 300    0 -300]
 [  85    0  -85]]

Sum of Hadarmard product: 65
